aws_dbt_snowflake_project:
  outputs:
    dev:
      account: BTUNQPW-ZB94498
      database: AIRBNB
      password: Ananthkumarg16
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: sagar
      warehouse: COMPUTE_WH
  target: dev
